TARGET = iphone:13.3:12.0

ARCHS = arm64 arm64e

include $(THEOS)/makefiles/common.mk

APPLICATION_NAME = ChusmaApp

ChusmaApp_FILES = main.m
ChusmaApp_FRAMEWORKS = UIKit CoreGraphics
ChusmaApp_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/application.mk
